In [10]:
import numpy as np

data = np.load("C:/Users/nicho/Desktop/Nick-Weiss-CSC-Thesis-2526/decoded/cnn_decoded/P32/P32_segments.npz", allow_pickle=True)


print(data.files)  # shows what's inside


['class_list', 'n_classes', 'seg_label', 'seg_t_start', 'seg_t_end', 'seg_dur', 'seg_n', 'counts', 'durations']


In [9]:
print(data['y_decoded'][10010:10020])
print(data['y_pred_smooth'][10010:10020])
print(data['y_true'][10010:10020])

[2 2 2 2 2 2 2 2 2 0]
[2 2 2 2 2 2 2 0 0 0]
[2 2 2 2 2 0 0 0 0 0]
